/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.Db;
import hr.*;
import inventory.*;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sukhmanbir
 */
public class Gui_UI extends javax.swing.JFrame {

    /**
     * Creates new form Final_Assignment_UI
     */
    public Gui_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        greetingLabel = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        searchTabPanel = new javax.swing.JTabbedPane();
        employeePanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        monthLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        commissionRateLabel = new javax.swing.JLabel();
        grossSalesLabel = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        commissionRate = new javax.swing.JTextField();
        position = new javax.swing.JTextField();
        day = new javax.swing.JSpinner();
        month = new javax.swing.JSpinner();
        year = new javax.swing.JTextField();
        grossSales = new javax.swing.JTextField();
        addEmployeeButton = new javax.swing.JButton();
        commissionSalesEmployeeLabel = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchCommissionSalesEmployeeLabel = new javax.swing.JLabel();
        searchProductLabel = new javax.swing.JLabel();
        searchEmployeeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchEmployeeButton = new javax.swing.JButton();
        searchProductButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchEmployeeResult = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchProductResult = new javax.swing.JTextArea();
        searchEmployeeComboBox = new javax.swing.JComboBox();
        searchProductComboBox = new javax.swing.JComboBox();
        fetchEmployeeButton = new javax.swing.JButton();
        fetchProductButton = new javax.swing.JButton();
        productPanel = new javax.swing.JPanel();
        productLabel = new javax.swing.JLabel();
        productNameLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        manufacturerLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        partNumLabel = new javax.swing.JLabel();
        productCostLabel = new javax.swing.JLabel();
        productPriceLabel = new javax.swing.JLabel();
        productMarkupLabel = new javax.swing.JLabel();
        productMarkup = new javax.swing.JTextField();
        productPrice = new javax.swing.JTextField();
        productCost = new javax.swing.JTextField();
        partNum = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        manufacturer = new javax.swing.JTextField();
        category = new javax.swing.JTextField();
        productName = new javax.swing.JTextField();
        addProductButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        greetingLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        greetingLabel.setText("Management System");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(greetingLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(greetingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        bottomPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitButton.setText("Exit");
        exitButton.setToolTipText("Close");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(30, 30, 30))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        employeePanel.setToolTipText("Employee Tab");

        firstNameLabel.setText("First Name:");

        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        lastNameLabel.setText("Last Name:");

        ageLabel.setText("Age:");

        positionLabel.setText("Position:");

        dayLabel.setText("Day of Hire:");

        monthLabel.setText("Month of Hire:");

        yearLabel.setText("Year of Hire:");

        commissionRateLabel.setText("Commission Rate:");

        grossSalesLabel.setText("Gross Sales:");

        day.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        month.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        addEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addEmployeeButton.setText("Add Employee");
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });

        commissionSalesEmployeeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        commissionSalesEmployeeLabel.setText("Add Commission Sales Employee");

        javax.swing.GroupLayout employeePanelLayout = new javax.swing.GroupLayout(employeePanel);
        employeePanel.setLayout(employeePanelLayout);
        employeePanelLayout.setHorizontalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePanelLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(commissionRateLabel)
                            .addComponent(ageLabel)
                            .addComponent(positionLabel)
                            .addComponent(dayLabel)
                            .addComponent(monthLabel)
                            .addComponent(yearLabel)
                            .addComponent(grossSalesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(position, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grossSales, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(commissionRate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(month, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(day, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(year, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameLabel))
                        .addGap(40, 40, 40)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstName)
                            .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(commissionSalesEmployeeLabel)))
                .addGap(156, 156, 156))
        );
        employeePanelLayout.setVerticalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(commissionSalesEmployeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionLabel)
                    .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayLabel)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthLabel)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commissionRateLabel)
                    .addComponent(commissionRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grossSalesLabel)
                    .addComponent(grossSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addEmployeeButton))
        );

        searchTabPanel.addTab("Employee", employeePanel);

        searchPanel.setToolTipText("Search Tab");

        searchCommissionSalesEmployeeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchCommissionSalesEmployeeLabel.setText("Search Commission Sales Employee");

        searchProductLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchProductLabel.setText("Search Product");

        searchEmployeeLabel.setText("Choose name of the employee");

        jLabel2.setText("Choose name of the product");

        searchEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchEmployeeButton.setText("Search Employee");
        searchEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmployeeButtonActionPerformed(evt);
            }
        });

        searchProductButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchProductButton.setText("Search Product");
        searchProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductButtonActionPerformed(evt);
            }
        });

        searchEmployeeResult.setColumns(20);
        searchEmployeeResult.setRows(5);
        jScrollPane1.setViewportView(searchEmployeeResult);

        searchProductResult.setColumns(20);
        searchProductResult.setRows(5);
        jScrollPane2.setViewportView(searchProductResult);

        searchEmployeeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmployeeComboBoxActionPerformed(evt);
            }
        });

        searchProductComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductComboBoxActionPerformed(evt);
            }
        });

        fetchEmployeeButton.setText("Fetch Data");
        fetchEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchEmployeeButtonActionPerformed(evt);
            }
        });

        fetchProductButton.setText("Fetch Data");
        fetchProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(searchEmployeeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchProductButton)
                                .addGap(63, 63, 63))
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addComponent(searchCommissionSalesEmployeeLabel)
                                .addGap(90, 90, 90)
                                .addComponent(searchProductLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE))
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addComponent(searchEmployeeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fetchEmployeeButton))
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(searchEmployeeLabel)))
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fetchProductButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(120, 120, 120))))))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCommissionSalesEmployeeLabel)
                    .addComponent(searchProductLabel))
                .addGap(35, 35, 35)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchEmployeeLabel)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchEmployeeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fetchEmployeeButton)
                    .addComponent(fetchProductButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchEmployeeButton)
                    .addComponent(searchProductButton))
                .addGap(24, 24, 24))
        );

        searchTabPanel.addTab("Search", searchPanel);

        productPanel.setToolTipText("Product Tab");

        productLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productLabel.setText("Add Product");

        productNameLabel.setText("Product Name:");

        categoryLabel.setText("Category:");

        manufacturerLabel.setText("Manufacturer:");

        descriptionLabel.setText("Description:");

        partNumLabel.setText("Part Number:");

        productCostLabel.setText("Product Cost:");

        productPriceLabel.setText("Product Price:");

        productMarkupLabel.setText("Product Markup:");

        partNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partNumActionPerformed(evt);
            }
        });

        addProductButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addProductButton.setText("Add Product");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productPanelLayout = new javax.swing.GroupLayout(productPanel);
        productPanel.setLayout(productPanelLayout);
        productPanelLayout.setHorizontalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productPanelLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(productLabel))
                    .addGroup(productPanelLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productPanelLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(productPanelLayout.createSequentialGroup()
                                .addComponent(descriptionLabel)
                                .addGap(32, 32, 32)
                                .addComponent(description))
                            .addGroup(productPanelLayout.createSequentialGroup()
                                .addComponent(partNumLabel)
                                .addGap(25, 25, 25)
                                .addComponent(partNum))
                            .addGroup(productPanelLayout.createSequentialGroup()
                                .addComponent(productCostLabel)
                                .addGap(23, 23, 23)
                                .addComponent(productCost))
                            .addGroup(productPanelLayout.createSequentialGroup()
                                .addComponent(productPriceLabel)
                                .addGap(22, 22, 22)
                                .addComponent(productPrice))
                            .addGroup(productPanelLayout.createSequentialGroup()
                                .addComponent(productMarkupLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(productMarkup))
                            .addGroup(productPanelLayout.createSequentialGroup()
                                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productNameLabel)
                                    .addComponent(categoryLabel))
                                .addGap(18, 18, 18)
                                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(productName)
                                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(productPanelLayout.createSequentialGroup()
                                .addComponent(manufacturerLabel)
                                .addGap(18, 18, 18)
                                .addComponent(manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        productPanelLayout.setVerticalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(productLabel)
                .addGap(18, 18, 18)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameLabel)
                    .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturerLabel)
                    .addComponent(manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionLabel)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partNumLabel)
                    .addComponent(partNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productCostLabel)
                    .addComponent(productCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productPriceLabel)
                    .addComponent(productPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productMarkupLabel)
                    .addComponent(productMarkup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(addProductButton))
        );

        searchTabPanel.addTab("Product", productPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchTabPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTabPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void partNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partNumActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
        try{
            //check if all the fields are input
            if(firstName.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter first name!");
            }
            if(lastName.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter last name!");
            }
            if(age.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter age!");
            }
            if(position.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter position!");
            }
            if(year.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter year of hire!");
            }
            if(month.getValue().toString().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter month of hire!");
            }
            if(day.getValue().toString().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter day of hire!");
            }
            if(commissionRate.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter commission Rate!");
            }
            if(grossSales.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter gross sales!");
            }
            else
            {
            Db f = new Db();
            ResultSet res = null;
            
                Employee e = new CommissionSalesEmployee(firstName.getText(), lastName.getText(), Integer.parseInt(age.getText()),
                    position.getText() , Integer.parseInt(year.getText()), Integer.parseInt(month.getValue().toString()), 
                    Integer.parseInt(day.getValue().toString()), Double.parseDouble(commissionRate.getText()), 
                    Double.parseDouble(grossSales.getText()));
                f.add((CommissionSalesEmployee) e);
          
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed

        try{
            
     
            if(productName.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Please enter Product name");
            }
            if(manufacturer.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Please enter Manufacturer name");
            }
            if(description.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Please enter Description");
            }
            if(partNum.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Please enter Part Num");
            }
            if(productCost.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Please enter Product Cost");
            }
            if(productPrice.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Please enter Product Price ");
            }
          
            else
            {
                   
                Db f = new Db();
                ResultSet res = null;
                Product p;
                p = new Product(productName.getText(),category.getText(), manufacturer.getText(),description.getText(), partNum.getText(),Double.parseDouble(productCost.getText()),Double.parseDouble(productPrice.getText()),Double.parseDouble(productMarkup.getText()));
                f.add(p);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void searchEmployeeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmployeeComboBoxActionPerformed
        
    }//GEN-LAST:event_searchEmployeeComboBoxActionPerformed

    private void searchProductComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductComboBoxActionPerformed
        
    }//GEN-LAST:event_searchProductComboBoxActionPerformed

    private void fetchEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchEmployeeButtonActionPerformed
        Db f = new Db();
        ResultSet res = null;
        res = f.populateEmployeeDropdown();
        
        try{
        while(res.next()){
        searchEmployeeComboBox.addItem(res.getString("firstName") + " " + res.getString("lastName"));
        }
        }
        catch(SQLException | HeadlessException ex)
        {
              JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        System.out.println(searchEmployeeComboBox.getItemCount());
    }//GEN-LAST:event_fetchEmployeeButtonActionPerformed

    private void fetchProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchProductButtonActionPerformed
        Db f = new Db();
        ResultSet res = null;
        
        res = f.populateProductDropdown();
        
        try{
        while(res.next()){
        searchProductComboBox.addItem(res.getString("name"));
        }
        }
        catch(SQLException | HeadlessException ex)
        {
              JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        System.out.println(searchProductComboBox.getItemCount());
    }//GEN-LAST:event_fetchProductButtonActionPerformed

    private void searchEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmployeeButtonActionPerformed
        Db f = new Db();
        ResultSet res = null;
        
        res = f.find("employees", "concat(firstName, ' ', lastName)", searchEmployeeComboBox.getSelectedItem().toString());
        
        try{
            if(res.next()){
                Employee emp = new CommissionSalesEmployee(res.getString("firstName"), res.getString("firstName"), res.getInt("age"),
                res.getString("position"), res.getInt("year"), res.getInt("month"), res.getInt("day"),
                res.getDouble("comRate"), res.getDouble("sales"));
                searchEmployeeResult.setText(emp.toString());
            }
            else{
              JOptionPane.showMessageDialog(null,"NO DATA FOUND");
            }
        }
        catch(SQLException | HeadlessException ex)
        {
              JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_searchEmployeeButtonActionPerformed

    private void searchProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductButtonActionPerformed
        Db f = new Db();
        ResultSet res = null;
        
        res = f.find("product", "name", searchProductComboBox.getSelectedItem().toString());
        
        try{
            if(res.next()){
                Product p = new Product(res.getString("name"), res.getString("category"), res.getString("manufacturer"),
                res.getString("description"), res.getString("partNum"), res.getDouble("productCost"),
                res.getDouble("productPrice"), res.getDouble("productMarkup"));
                searchProductResult.setText(p.toString());
            }
            else{
              JOptionPane.showMessageDialog(null,"NO DATA FOUND");
            }
        }
        catch(SQLException | HeadlessException ex)
        {
              JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_searchProductButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               Gui_UI Gui = new Gui_UI();
               Gui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
               Gui.pack();
               Gui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JButton addProductButton;
    private javax.swing.JTextField age;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JTextField category;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField commissionRate;
    private javax.swing.JLabel commissionRateLabel;
    private javax.swing.JLabel commissionSalesEmployeeLabel;
    private javax.swing.JSpinner day;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField description;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JPanel employeePanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton fetchEmployeeButton;
    private javax.swing.JButton fetchProductButton;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel greetingLabel;
    private javax.swing.JTextField grossSales;
    private javax.swing.JLabel grossSalesLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField manufacturer;
    private javax.swing.JLabel manufacturerLabel;
    private javax.swing.JSpinner month;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField partNum;
    private javax.swing.JLabel partNumLabel;
    private javax.swing.JTextField position;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JTextField productCost;
    private javax.swing.JLabel productCostLabel;
    private javax.swing.JLabel productLabel;
    private javax.swing.JTextField productMarkup;
    private javax.swing.JLabel productMarkupLabel;
    private javax.swing.JTextField productName;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JPanel productPanel;
    private javax.swing.JTextField productPrice;
    private javax.swing.JLabel productPriceLabel;
    private javax.swing.JLabel searchCommissionSalesEmployeeLabel;
    private javax.swing.JButton searchEmployeeButton;
    private javax.swing.JComboBox searchEmployeeComboBox;
    private javax.swing.JLabel searchEmployeeLabel;
    private javax.swing.JTextArea searchEmployeeResult;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JButton searchProductButton;
    private javax.swing.JComboBox searchProductComboBox;
    private javax.swing.JLabel searchProductLabel;
    private javax.swing.JTextArea searchProductResult;
    private javax.swing.JTabbedPane searchTabPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField year;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
